package project;

import java.util.ArrayList;

public final class Order implements java.io.Serializable {
    /**
     * The username of the customer
     */
    private String customerUsername;
    /**
     * The items that were ordered
     */
    private ArrayList<Shipment> orderedItems;

    /**
     * The authorization number generated by the bank
     */
    private int authorizationNumber;

    public enum OrderStatus {
        Ordered,
        Ready,
        Shipped
    }

    /**
     * The status of the order
     */
    private OrderStatus orderStatus;

    /**
     * Creates a new order
     *
     * @param customerUsername    the username of the customer
     * @param orderedItems        the items that were ordered
     * @param authorizationNumber the authorization number generated by the bank
     */
    public Order(String customerUsername, ArrayList<Shipment> orderedItems, int authorizationNumber) {
        this.customerUsername = customerUsername;
        this.orderedItems = orderedItems;
        this.authorizationNumber = authorizationNumber;
        this.orderStatus = OrderStatus.Ordered;
    }

    public ArrayList<Shipment> getOrderedItems() {
        return orderedItems;
    }

    public void setOrderedItems(ArrayList<Shipment> orderedItems) {
        this.orderedItems = orderedItems;
    }

    public String getCustomerUsername() {
        return customerUsername;
    }

    public void setCustomerUsername(String customerUsername) {
        this.customerUsername = customerUsername;
    }

    public int getAuthorizationNumber() {
        return authorizationNumber;
    }

    public OrderStatus getOrderStatus() {
        return orderStatus;
    }

    public void setOrderStatus(OrderStatus orderStatus) {
        this.orderStatus = orderStatus;
    }

    @Override
    public String toString() {
        StringBuilder output = new StringBuilder();
        int i = 1;
        for (Shipment shipment : this.getOrderedItems()) {
            output.append(String.format("Item %d: %s - Amount: %d\n", i, shipment.getItem().getName(), shipment.getAmount()));
            i++;
        }
        output.append(String.format("\nOrder Status: %s", this.getOrderStatus().toString()));
        return output.toString();
    }
}
